function randomString() {
    var chars =
        "0123456789ABCDEFGHIJKLMNOPQRSTUVWXTZabcdefghiklmnopqrstuvwxyz".split("");

    length = Math.floor(Math.random() * chars.length);
    var str = "";
    for (var i = 0; i < length; i++) {
        str += chars[Math.floor(Math.random() * chars.length)];
    }
    return str;
}

let laptopsDetails = [{
        id: randomString(),
        brand: "HP",
        model: "SPECTRE X360",
        image: "https://m.media-amazon.com/images/I/814pRVG5BmL.jpg",
        description: "Premium convertible laptop with high-end performance.",
        specs: [
            { name: "CPU", value: "INTEL CORE I7-1355U" },
            { name: "RAM", value: "16GB LPDDR5" },
            { name: "STORAGE", value: "1TB SSD" },
            { name: "DISPLAY", value: "13.5-INCH 3K OLED" },
            { name: "BATTERY LIFE", value: "16 HOURS" },
            { name: "OS", value: "WINDOWS 11 HOME" },
            { name: "WEIGHT", value: "1.34 KG" },
            { name: "GPU", value: "INTEL IRIS XE" },
            { name: "TOUCHSCREEN", value: "YES" },
            { name: "FINGERPRINT", value: "YES" },
            { name: "PORTS", value: "2X USB-C, 1X USB-A" },
            { name: "BUILD MATERIAL", value: "ALUMINUM" },
            { name: "CHARGING", value: "FAST CHARGING SUPPORTED" },
            { name: "SPEAKERS", value: "BANG & OLUFSEN" },
            { name: "CAMERA", value: "5MP IR CAMERA" },
            { name: "BACKLIT KEYBOARD", value: "YES" },
            { name: "THERMALS", value: "DUAL FAN" },
            { name: "AI FEATURES", value: "HP PRESENCE" },
            { name: "WIFI", value: "WIFI 6E" },
            { name: "BLUETOOTH", value: "5.3" }
        ],
        ratings: [
            { name: "CPU", value: 5 },
            { name: "RAM", value: 5 },
            { name: "STORAGE", value: 5 },
            { name: "DISPLAY", value: 5 },
            { name: "BATTERY LIFE", value: 5 },
            { name: "OS", value: 4 },
            { name: "WEIGHT", value: 4 },
            { name: "GPU", value: 4 },
            { name: "TOUCHSCREEN", value: 5 },
            { name: "FINGERPRINT", value: 5 },
            { name: "PORTS", value: 4 },
            { name: "BUILD MATERIAL", value: 5 },
            { name: "CHARGING", value: 5 },
            { name: "SPEAKERS", value: 5 },
            { name: "CAMERA", value: 5 },
            { name: "BACKLIT KEYBOARD", value: 5 },
            { name: "THERMALS", value: 4 },
            { name: "AI FEATURES", value: 5 },
            { name: "WIFI", value: 5 },
            { name: "BLUETOOTH", value: 5 }
        ],
        score: 96,
        price: 124999,
        offerPrice: 114999,
        url: "https://www.amazon.in/hp-spectre-x360/s?k=hp+spectre+x360"
    },
    {
        id: randomString(),
        brand: "HP",
        model: "SPECTRE X300",
        image: "https://www.hp.com/content/dam/sites/worldwide/personal-computers/consumer/laptops-and-2-n-1s/spectre/version-2023/Get%20a%20fresh%20perspective%20_Desktop@2x.png",
        description: "HP SPECTRE X300 high-performance laptop with premium features.",
        specs: [
            { name: "CPU", value: "SNAPDRAGON X ELITE" },
            { name: "RAM", value: "32GB" },
            { name: "STORAGE", value: "1TB SSD" },
            { name: "DISPLAY", value: "15.6-INCH OLED" },
            { name: "BATTERY LIFE", value: "10 HOURS" },
            { name: "OS", value: "WINDOWS 11" },
            { name: "WEIGHT", value: "1.2 KG" },
            { name: "GPU", value: "NVIDIA RTX 3050" },
            { name: "BUILD", value: "MAGNESIUM" },
            { name: "KEYBOARD", value: "STANDARD" },
            { name: "PORTS", value: "USB-A, USB-C" },
            { name: "TOUCHPAD", value: "STANDARD" },
            { name: "CAMERA", value: "720P" },
            { name: "SPEAKERS", value: "DOLBY AUDIO" },
            { name: "CHARGING", value: "100W TYPE-C" },
            { name: "THERMALS", value: "DUAL FAN" },
            { name: "WIFI", value: "WIFI 7" },
            { name: "BLUETOOTH", value: "5.3" },
            { name: "SECURITY", value: "TPM 2.0" },
            { name: "AI FEATURES", value: "AI OPTIMIZATION" }
        ],
        ratings: [
            { name: "CPU", value: 4 },
            { name: "RAM", value: 4 },
            { name: "STORAGE", value: 3 },
            { name: "DISPLAY", value: 5 },
            { name: "BATTERY LIFE", value: 4 },
            { name: "OS", value: 4 },
            { name: "WEIGHT", value: 4 },
            { name: "GPU", value: 3 },
            { name: "BUILD", value: 3 },
            { name: "KEYBOARD", value: 3 },
            { name: "PORTS", value: 3 },
            { name: "TOUCHPAD", value: 5 },
            { name: "CAMERA", value: 4 },
            { name: "SPEAKERS", value: 4 },
            { name: "CHARGING", value: 3 },
            { name: "THERMALS", value: 4 },
            { name: "WIFI", value: 4 },
            { name: "BLUETOOTH", value: 3 },
            { name: "SECURITY", value: 4 },
            { name: "AI FEATURES", value: 4 }
        ],
        score: 78,
        price: 101984,
        offerPrice: 94257,
        url: "https://www.amazon.in/s?k=hp+spectre+x300&crid=1VNBQ6ELA56J2&sprefix=hp+spectre+x300%2Caps%2C255&ref=nb_sb_noss"
    },

    {
        id: randomString(),
        brand: "DELL",
        model: "XPS 15 PLUS",
        image: "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/xps-notebooks/xps-15-9520/spi/black/ng/notebook-xps-15-9520-black-campaign-hero-504x350-ng.psd?fmt=jpg&wid=570&hei=400",
        description: "Powerful creator-focused laptop with immersive display.",
        specs: [
            { name: "CPU", value: "INTEL CORE I9-13900H" },
            { name: "RAM", value: "32GB DDR5" },
            { name: "STORAGE", value: "1TB NVME SSD" },
            { name: "DISPLAY", value: "15.6-INCH 4K UHD+ TOUCH" },
            { name: "BATTERY LIFE", value: "12 HOURS" },
            { name: "OS", value: "WINDOWS 11 PRO" },
            { name: "WEIGHT", value: "1.8 KG" },
            { name: "GPU", value: "NVIDIA RTX 4060" },
            { name: "BUILD MATERIAL", value: "ALUMINUM + GLASS" },
            { name: "PORTS", value: "4X USB-C, SD CARD" },
            { name: "CHARGING", value: "130W USB-C" },
            { name: "FINGERPRINT", value: "YES" },
            { name: "TOUCHPAD", value: "FORCEPAD" },
            { name: "THERMALS", value: "VAPOR CHAMBER" },
            { name: "WIFI", value: "WIFI 6E" },
            { name: "BLUETOOTH", value: "5.3" },
            { name: "KEYBOARD", value: "ZERO LATTICE" },
            { name: "CAMERA", value: "FHD IR CAMERA" },
            { name: "AI FEATURES", value: "DELL OPTIMIZER" },
            { name: "AUDIO", value: "QUAD SPEAKERS" }
        ],
        ratings: [
            { name: "CPU", value: 5 },
            { name: "RAM", value: 5 },
            { name: "STORAGE", value: 5 },
            { name: "DISPLAY", value: 5 },
            { name: "BATTERY LIFE", value: 4 },
            { name: "OS", value: 4 },
            { name: "WEIGHT", value: 3 },
            { name: "GPU", value: 5 },
            { name: "BUILD MATERIAL", value: 5 },
            { name: "PORTS", value: 4 },
            { name: "CHARGING", value: 4 },
            { name: "FINGERPRINT", value: 4 },
            { name: "TOUCHPAD", value: 5 },
            { name: "THERMALS", value: 4 },
            { name: "WIFI", value: 5 },
            { name: "BLUETOOTH", value: 5 },
            { name: "KEYBOARD", value: 4 },
            { name: "CAMERA", value: 4 },
            { name: "AI FEATURES", value: 4 },
            { name: "AUDIO", value: 5 }
        ],
        score: 91,
        price: 229999,
        offerPrice: 214999,
        url: "https://www.amazon.in/s?k=DELL+XPS+15+PLUS&crid=3OWSVVLSH0WKI&sprefix=dell+xps+15+plus%2Caps%2C298&ref=nb_sb_noss_1"
    },
    {
        id: randomString(),
        brand: "LENOVO",
        model: "LEGION 5 PRO",
        image: "https://rukminim2.flixcart.com/image/704/844/xif0q/computer/f/k/i/-original-imahcyp7wqu6sqgd.jpeg?q=90&crop=false",
        description: "High-performance gaming and productivity laptop.",
        specs: [
            { name: "CPU", value: "AMD RYZEN 7 6800H" },
            { name: "RAM", value: "16GB DDR5" },
            { name: "STORAGE", value: "1TB SSD" },
            { name: "DISPLAY", value: "16-INCH WQXGA 165HZ" },
            { name: "GPU", value: "NVIDIA RTX 3070" },
            { name: "BATTERY LIFE", value: "7 HOURS" },
            { name: "WEIGHT", value: "2.4 KG" },
            { name: "OS", value: "WINDOWS 11 HOME" },
            { name: "PORTS", value: "4X USB, HDMI, TYPE-C" },
            { name: "KEYBOARD", value: "4-ZONE RGB" },
            { name: "THERMALS", value: "LEGION COLD FRONT 4.0" },
            { name: "CAMERA", value: "720P HD" },
            { name: "CHARGING", value: "230W RAPID CHARGE" },
            { name: "WIFI", value: "WIFI 6" },
            { name: "BLUETOOTH", value: "5.2" },
            { name: "AUDIO", value: "NAHIMIC AUDIO" },
            { name: "BUILD MATERIAL", value: "ALUMINUM + PLASTIC" },
            { name: "TOUCHPAD", value: "PRECISION" },
            { name: "FINGERPRINT", value: "NO" },
            { name: "VR READY", value: "YES" }
        ],
        ratings: [
            { name: "CPU", value: 5 },
            { name: "RAM", value: 5 },
            { name: "STORAGE", value: 5 },
            { name: "DISPLAY", value: 5 },
            { name: "GPU", value: 5 },
            { name: "BATTERY LIFE", value: 3 },
            { name: "WEIGHT", value: 3 },
            { name: "OS", value: 4 },
            { name: "PORTS", value: 5 },
            { name: "KEYBOARD", value: 5 },
            { name: "THERMALS", value: 5 },
            { name: "CAMERA", value: 3 },
            { name: "CHARGING", value: 5 },
            { name: "WIFI", value: 4 },
            { name: "BLUETOOTH", value: 4 },
            { name: "AUDIO", value: 4 },
            { name: "BUILD MATERIAL", value: 4 },
            { name: "TOUCHPAD", value: 4 },
            { name: "FINGERPRINT", value: 1 },
            { name: "VR READY", value: 5 }
        ],
        score: 87,
        price: 152000,
        offerPrice: 139999,
        url: "https://www.amazon.in/s?k=LENOVO+LEGION+5+PRO&crid=3SS3OXQQDH4F3&sprefix=lenovo+legion+5+pro%2Caps%2C251&ref=nb_sb_noss_2"
    },
    {
        id: randomString(),
        brand: "APPLE",
        model: "MACBOOK AIR M2",
        image: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/mba13-skyblue-select-202503?wid=892&hei=820&fmt=jpeg&qlt=90&.v=M2RyY09CWXlTQUp1KzEveHR6VXNxcTQ1bzN1SitYTU83Mm9wbk1xa1lWN2h4SGtCQ2R3aStVaDRhL2VUV1NjdkJkRlpCNVhYU3AwTldRQldlSnpRa0lIV0Fmdk9rUlVsZ3hnNXZ3K3lEVlk",
        description: "Lightweight, silent and ultra-efficient Apple silicon laptop.",
        specs: [
            { name: "CPU", value: "APPLE M2 CHIP" },
            { name: "RAM", value: "8GB UNIFIED" },
            { name: "STORAGE", value: "512GB SSD" },
            { name: "DISPLAY", value: "13.6-INCH RETINA" },
            { name: "GPU", value: "10-CORE GPU" },
            { name: "BATTERY LIFE", value: "18 HOURS" },
            { name: "OS", value: "MACOS SONOMA" },
            { name: "WEIGHT", value: "1.24 KG" },
            { name: "PORTS", value: "2X THUNDERBOLT, MAGSAFE" },
            { name: "BUILD MATERIAL", value: "RECYCLED ALUMINUM" },
            { name: "TOUCH ID", value: "YES" },
            { name: "CAMERA", value: "1080P FACETIME HD" },
            { name: "AUDIO", value: "4-SPEAKER SYSTEM" },
            { name: "CHARGING", value: "MAGSAFE 30W" },
            { name: "WIFI", value: "WIFI 6" },
            { name: "BLUETOOTH", value: "5.3" },
            { name: "THERMALS", value: "FANLESS" },
            { name: "KEYBOARD", value: "MAGIC KEYBOARD" },
            { name: "TOUCHPAD", value: "FORCE TOUCH" },
            { name: "SUSTAINABILITY", value: "EPEAT GOLD" }
        ],
        ratings: [
            { name: "CPU", value: 5 },
            { name: "RAM", value: 4 },
            { name: "STORAGE", value: 4 },
            { name: "DISPLAY", value: 5 },
            { name: "GPU", value: 4 },
            { name: "BATTERY LIFE", value: 5 },
            { name: "OS", value: 5 },
            { name: "WEIGHT", value: 5 },
            { name: "PORTS", value: 3 },
            { name: "BUILD MATERIAL", value: 5 },
            { name: "TOUCH ID", value: 5 },
            { name: "CAMERA", value: 4 },
            { name: "AUDIO", value: 5 },
            { name: "CHARGING", value: 4 },
            { name: "WIFI", value: 4 },
            { name: "BLUETOOTH", value: 5 },
            { name: "THERMALS", value: 5 },
            { name: "KEYBOARD", value: 5 },
            { name: "TOUCHPAD", value: 5 },
            { name: "SUSTAINABILITY", value: 5 }
        ],
        score: 93,
        price: 134900,
        offerPrice: 119900,
        url: "https://www.amazon.in/s?k=apple+macbook+m2&crid=1HMCFP8W0N9PK&sprefix=Apple+Mac%2Caps%2C266&ref=nb_sb_ss_mvt-t11-ranker_3_9"
    },
    {
        id: randomString(),
        brand: "HP",
        model: "VICTUS 16",
        image: "https://rukminim2.flixcart.com/image/704/844/xif0q/computer/e/f/z/-original-imahcd9ndrxnbvkm.jpeg?q=90&crop=false",
        description: "Powerful mid-range gaming laptop with large screen.",
        specs: [
            { name: "CPU", value: "INTEL CORE I7 12700H" },
            { name: "RAM", value: "16GB DDR4" },
            { name: "STORAGE", value: "512GB SSD" },
            { name: "DISPLAY", value: "16.1-INCH FHD 144HZ" },
            { name: "GPU", value: "NVIDIA RTX 4060" },
            { name: "BATTERY LIFE", value: "6 HOURS" },
            { name: "WEIGHT", value: "2.4 KG" },
            { name: "OS", value: "WINDOWS 11 HOME" },
            { name: "PORTS", value: "USB-C, HDMI, RJ-45" },
            { name: "KEYBOARD", value: "BACKLIT" },
            { name: "THERMALS", value: "OMEN TEMPEST COOLING" },
            { name: "AUDIO", value: "BANG & OLUFSEN" },
            { name: "BUILD MATERIAL", value: "PLASTIC" },
            { name: "CAMERA", value: "720P HD" },
            { name: "TOUCHPAD", value: "MULTI-GESTURE" },
            { name: "CHARGING", value: "200W FAST CHARGE" },
            { name: "WIFI", value: "WIFI 6E" },
            { name: "BLUETOOTH", value: "5.2" },
            { name: "VR READY", value: "YES" },
            { name: "EXPANSION SLOT", value: "MICRO SD" }
        ],
        ratings: [
            { name: "CPU", value: 5 },
            { name: "RAM", value: 4 },
            { name: "STORAGE", value: 4 },
            { name: "DISPLAY", value: 5 },
            { name: "GPU", value: 5 },
            { name: "BATTERY LIFE", value: 3 },
            { name: "WEIGHT", value: 3 },
            { name: "OS", value: 4 },
            { name: "PORTS", value: 4 },
            { name: "KEYBOARD", value: 4 },
            { name: "THERMALS", value: 4 },
            { name: "AUDIO", value: 4 },
            { name: "BUILD MATERIAL", value: 3 },
            { name: "CAMERA", value: 3 },
            { name: "TOUCHPAD", value: 4 },
            { name: "CHARGING", value: 4 },
            { name: "WIFI", value: 5 },
            { name: "BLUETOOTH", value: 5 },
            { name: "VR READY", value: 5 },
            { name: "EXPANSION SLOT", value: 4 }
        ],
        score: 85,
        price: 114999,
        offerPrice: 104999,
        url: "https://www.amazon.in/s?k=Hp+Victus+16&crid=M7GF23GMDSUV&sprefix=hp+victus+16%2Caps%2C266&ref=nb_sb_noss_1"
    },

    {
        id: randomString(),
        brand: "ASUS",
        model: "VIVOBOOK S15 OLED",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJWWX1UMceb72VsWQikpVOJDH6c5X6wzMJEA&s",
        description: "Slim OLED laptop for everyday use and vibrant visuals.",
        specs: [
            { name: "CPU", value: "INTEL CORE I5 12500H" },
            { name: "RAM", value: "16GB LPDDR5" },
            { name: "STORAGE", value: "512GB SSD" },
            { name: "DISPLAY", value: "15.6-INCH OLED 2.8K" },
            { name: "GPU", value: "INTEL IRIS XE" },
            { name: "BATTERY LIFE", value: "8 HOURS" },
            { name: "OS", value: "WINDOWS 11 HOME" },
            { name: "WEIGHT", value: "1.7 KG" },
            { name: "PORTS", value: "HDMI, USB-C, USB-A" },
            { name: "BUILD MATERIAL", value: "ALUMINUM ALLOY" },
            { name: "CAMERA", value: "1080P" },
            { name: "TOUCHPAD", value: "LARGE PRECISION" },
            { name: "WIFI", value: "WIFI 6E" },
            { name: "BLUETOOTH", value: "5.3" },
            { name: "AUDIO", value: "HARMAN KARDON" },
            { name: "CHARGING", value: "65W USB-C" },
            { name: "FINGERPRINT", value: "YES" },
            { name: "THERMALS", value: "ICECOOL PLUS" },
            { name: "COLOR", value: "MIDNIGHT BLACK" },
            { name: "SUSTAINABILITY", value: "ENERGY STAR" }
        ],
        ratings: [
            { name: "CPU", value: 4 },
            { name: "RAM", value: 4 },
            { name: "STORAGE", value: 4 },
            { name: "DISPLAY", value: 5 },
            { name: "GPU", value: 3 },
            { name: "BATTERY LIFE", value: 4 },
            { name: "OS", value: 4 },
            { name: "WEIGHT", value: 4 },
            { name: "PORTS", value: 4 },
            { name: "BUILD MATERIAL", value: 5 },
            { name: "CAMERA", value: 4 },
            { name: "TOUCHPAD", value: 4 },
            { name: "WIFI", value: 5 },
            { name: "BLUETOOTH", value: 5 },
            { name: "AUDIO", value: 4 },
            { name: "CHARGING", value: 4 },
            { name: "FINGERPRINT", value: 5 },
            { name: "THERMALS", value: 4 },
            { name: "COLOR", value: 5 },
            { name: "SUSTAINABILITY", value: 5 }
        ],
        score: 89,
        price: 84990,
        offerPrice: 78990,
        url: "https://www.amazon.in/s?k=asus+vivobook+s15+oled&crid=31UTCNSXMRPC9&sprefix=asus+vivibook+s15+oled%2Caps%2C274&ref=nb_sb_ss_mvt-t11-ranker_1_22"
    },

    {
        id: randomString(),
        brand: "MSI",
        model: "MODERN 14",
        image: "https://asset.msi.com/resize/image/global/product/product_16703185422b9082c175f523ab1d49ed0a63b717bf.png62405b38c58fe0f07fcef2367d8a9ba1/600.png",
        description: "Lightweight and sleek for students and professionals.",
        specs: [
            { name: "CPU", value: "INTEL CORE I5 1240P" },
            { name: "RAM", value: "8GB DDR4" },
            { name: "STORAGE", value: "512GB SSD" },
            { name: "DISPLAY", value: "14-INCH FHD IPS" },
            { name: "GPU", value: "INTEL IRIS XE" },
            { name: "BATTERY LIFE", value: "10 HOURS" },
            { name: "WEIGHT", value: "1.3 KG" },
            { name: "OS", value: "WINDOWS 11 HOME" },
            { name: "PORTS", value: "USB-C, HDMI, USB-A" },
            { name: "BUILD MATERIAL", value: "METAL" },
            { name: "CAMERA", value: "720P HD" },
            { name: "TOUCHPAD", value: "MULTI-GESTURE" },
            { name: "WIFI", value: "WIFI 6" },
            { name: "BLUETOOTH", value: "5.2" },
            { name: "AUDIO", value: "HI-RES AUDIO" },
            { name: "CHARGING", value: "65W ADAPTER" },
            { name: "FINGERPRINT", value: "YES" },
            { name: "KEYBOARD", value: "WHITE BACKLIT" },
            { name: "SPEAKERS", value: "STEREO" },
            { name: "THERMALS", value: "COOLER BOOST" }
        ],
        ratings: [
            { name: "CPU", value: 4 },
            { name: "RAM", value: 3 },
            { name: "STORAGE", value: 4 },
            { name: "DISPLAY", value: 4 },
            { name: "GPU", value: 3 },
            { name: "BATTERY LIFE", value: 4 },
            { name: "WEIGHT", value: 5 },
            { name: "OS", value: 4 },
            { name: "PORTS", value: 4 },
            { name: "BUILD MATERIAL", value: 5 },
            { name: "CAMERA", value: 3 },
            { name: "TOUCHPAD", value: 4 },
            { name: "WIFI", value: 4 },
            { name: "BLUETOOTH", value: 4 },
            { name: "AUDIO", value: 4 },
            { name: "CHARGING", value: 4 },
            { name: "FINGERPRINT", value: 5 },
            { name: "KEYBOARD", value: 4 },
            { name: "SPEAKERS", value: 3 },
            { name: "THERMALS", value: 4 }
        ],
        score: 82,
        price: 62990,
        offerPrice: 59990,
        url: "https://www.amazon.in/s?k=msi+modern+14&crid=F044ZB9FOTXW&sprefix=msi+modern+14%2Caps%2C268&ref=nb_sb_noss_2"
    },
]


export default laptopsDetails;